database:
  host: mysql
  port: 3306
  user: root
  password: root
  databaseName: inu_backyard
client:
  auth:
    session:
      prefix: $
      secret: secret
      maxAge: 604800 # 7 days in second unit
    turnstile:
      secretKey: 2x0000000000000000000000000000000AA
  cors:
    AllowOrigins:
      - 'http://localhost:3000'
