apiVersion: v1
kind: ConfigMap
metadata:
  name: inu-backyard-config-map
data:
  config.yml: |
    database:
      host: <HOST>
      port: <PORT>
      user: <USER>
      password: <PASSWORD>
      databaseName: <DATABASE_NAME>
    client:
      auth:
        session:
          prefix: <PREFIX>
          secret: <SECRET>
          maxAge: <MAX_AGE>
          cookieName: <COOKIE_NAME>
      cors:
        AllowOrigins:
          - <ORIGIN>
